## Handwritten Numbers Using backpropogation
In this notebook we will be hardcoding the neural network which will detect the number in a image

Importing the packages and libraries

In [5]:
import pandas as pd
import numpy as np
import time 
import os
import warnings

Importing the dataset in the notebook and visualising it

In [2]:
train_df = pd.read_csv(r'C:/Users/Yash Phadke/OneDrive/Desktop/ML/back_prop/train.csv')
test_df = pd.read_csv(r'C:/Users/Yash Phadke/OneDrive/Desktop/ML/back_prop/test.csv')
train_np = train_df.to_numpy()
test_np = test_df.to_numpy()
test = train_np.T[0]

In [3]:
test_df.head()

,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [4]:
train_df.head()

,label,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [5]:
print(test)

[1 0 1 ... 7 6 9]

Defining the activation function

In [6]:
def sig(x):
    g = 1/(1 + np.exp(-x))
    return g

Here we define the function for making the layers in a NN . The inputs for the function are 
- number of neurons 
- input activation 
- weights 
- bias

In [7]:
def layer(n,a_i,w,b):
    j = 0 
    a_t =[]
    for j in range(n):
        a = np.dot(w[j],a_i) + b[j]
        a_t.append(a)
    a_o = np.array(a_t)
    return a_o

<img src ="C:/Users/Yash Phadke/OneDrive/Desktop/ML/back_prop/A-graphical-representation-of-a-MLP-with-N-I-2-input-neurons-L-2-hidden-layers-made.png" alt="Alternative text"/>

Here we define the structure of the NN which will contain 2 hidden layers each of 16 neurons and the output layer having 10 neurons each one for a number

In [8]:
def structure(array):
    w_1 = np.random.uniform(-0.5,0.5,(16,len(array)))
    b_1 = np.random.uniform(-0.5,0.5,16)
    a_1 = layer(16,array,w_1,b_1)
    w_2 = np.random.uniform(-0.5,0.5,(16,len(a_1)))
    b_2 = np.random.uniform(-0.5,0.5,16)
    a_2 = layer(16,sig(a_1),w_2,b_2)
    w_3 = np.random.uniform(-0.5,0.5,(10,len(a_2)))
    b_3 = np.random.uniform(-0.5,0.5,10)
    a_3 = layer(10,sig(a_2),w_3,b_3)
    return sig(a_3),w_1,w_2,w_3,b_1,b_2,b_3

In [10]:
final,w_1,w_2,w_3,b_1,b_2,b_3 =structure(test_np[0])
warnings.filterwarnings('ignore')
print(final)

[0.44244381 0.24390937 0.7081568  0.81544841 0.35283773 0.61470555
 0.32308328 0.37429445 0.68252177 0.30291637]